### ISSUE TITLE
V2 can´t start ownfoil container

### ISSUE THREAD

**Issue by fettesb** [a1ex4/ownfoil#65]
Starting ownfoil
ownfoil:x:1000:ownfoil
ownfoil:x:1000:1000:Linux User,,,:/home/ownfoil:/sbin/nologin
Starting ownfoil
warning: The following paths are not up to date and were left despite sparse patterns:
	DE.de.json
After fixing the above paths, you may want to run `git sparse-checkout reapply`.

**Comment by HenryBaby** [comment]
I had this same issue when I migrated from V1 to V2. I'm not quite sure how I fixed it, but I was running things from portainer. I removed and cleaned everything, including my volumes (remember to backup before doing this), and then started the container fresh.

Again, not sure what helped.

**Comment by FunsKiTo** [comment]
So, here's what happened to me. I was checking the logs and noticed that the container seem to be stuck at the starting stage. To resolve this, I decided to restart the container and got the same error. I think this error occurred because Docker was building, and that process can take some time, maybe depending on the size of your library.

As @HenryBaby suggested, the best approach would be to remove the container and its volumes. Afterward, launch it again and give it time to build.

**Comment by fettesb** [comment]
I did a clean install and let it sit for an hour
Log:
Starting ownfoil

after an hour i try to reach http://192.168.178.117:8465 but i get
ERR_CONNECTION_REFUSED

so i restartet the Container and let it sit for an hour
Log:
ownfoil:x:1000:ownfoil
ownfoil:x:1000:1000:Linux User,,,:/home/ownfoil:/sbin/nologin
Starting ownfoil
warning: The following paths are not up to date and were left despite sparse patterns:
	US.en.json
After fixing the above paths, you may want to run `git sparse-checkout reapply`.

Unfortunately, none of that helped.
any ideas?

**Comment by a1ex4** [comment]
This can happen if the container was not stopped cleanly or basically stopped at the wrong time. To fix it you just need to recreate the container (docker rm ownfoil and docker-compose up -d again) and that should fix it.

**Comment by fettesb** [comment]
i use portainer and deleted all images and container and the stack. Did a reboot and started fresh. Same thing happend again.

my library has a file size of 28 files

**Comment by fettesb** [comment]
<img width="878" alt="SCR-20231102-qjwm" src="https://github.com/a1ex4/ownfoil/assets/38019912/8b206b3f-b35e-4c0f-b77e-e2328c37c1e9">

**Comment by FunsKiTo** [comment]
The container is generating a tmp.pack file that occupies multiple gigabytes inside the "/app/data/titledb/.git/objects/pack" directory. It never completes, so I stopped it when it reached 20GB.

**Comment by a1ex4** [comment]
Thanks, on startup Ownfoil updates the locally cloned blawar/titledb, my guess is that there has been many changes to titledb since the last time the image was built. I added some mitigations to the update issues, and rebuilt the image so the delta won't be too much to handle (20GB+ pack file...).

Could you try the latest image?

**Comment by fettesb** [comment]
i deployed a new stack. No Problems at all. Ownfoil is up and running again. Thanks

**Comment by acaltas** [comment]
took some times after i created the container go get back access to the WebGui... but its working
i still have a lot of Unrecognized games.. but its seems tinfoil website has some errors

**Comment by FoUStep** [comment]
[traceback-ownfoilv2.log](https://github.com/a1ex4/ownfoil/files/13335142/traceback-ownfoilv2.log)

I've been running a HTTP v1 for a while. Decided to try v2. The attached log file (errors) is what I get when trying to go to the Web UI on port 8465.

Is there another way to pre-config it on CLI?

**Comment by a1ex4** [comment]
@FoUStep should be fixed by latest commit.

**Comment by FoUStep** [comment]
> @FoUStep should be fixed by latest commit.

`ownfoilv2      | HEAD is now at 315bd23 meta
ownfoilv2      | Your branch is up to date with 'origin/master'.
ownfoilv2      | Already on 'master'
ownfoilv2      | Already up to date.`

Unfortunately the issue still persists.

**Comment by P-C-R** [comment]
@a1ex4 same issue here: 
ownfoil:x:1000:ownfoil
ownfoil:x:1000:1000:Linux User,,,:/home/ownfoil:/sbin/nologin
Starting ownfoil
HEAD is now at 315bd23 meta
Your branch is up to date with 'origin/master'.

**Comment by P-C-R** [comment]
NVM. Takes just over 30min for inital start.

**Comment by a1ex4** [comment]
I changed how the initial start is done, to avoid being stuck for ages retrieving the latest titledb, should be fixed now but feel free to reopen.
